default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: guru

test:
  <<: *default
  database: guru_test
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { '' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>